import { describe, expect, it } from "vitest";
import { DYSFLOW_MCP_TOOL_NAMES } from "../../../src/adapters/mcp/mcp-tool-registry";
import { getToolDefinition } from "../../../src/adapters/mcp/tool-parity-registry";

/**
 * Contract test for #544: the description advertised for every MCP tool must be a
 * real per-tool contract a consuming agent can act on — NOT the autogenerated
 * parity boilerplate ("Dysflow MCP tool X; … implemented via Dysflow core
 * services.").
 */
describe("MCP tool descriptions are real per-tool contracts (#544)", () => {
  it("no tool advertises the parity boilerplate description", () => {
    const offenders: string[] = [];
    for (const name of DYSFLOW_MCP_TOOL_NAMES) {
      const description = getToolDefinition(name).description;
      const isBoilerplate =
        description.startsWith("Dysflow MCP tool ") ||
        /implemented via Dysflow core services/i.test(description) ||
        /tracked for parity/i.test(description);
      if (isBoilerplate) offenders.push(name);
    }
    expect(
      offenders,
      `These tools still advertise boilerplate descriptions: ${offenders.join(", ")}`,
    ).toEqual([]);
  });

  it("every tool description is reasonably descriptive", () => {
    const tooShort: string[] = [];
    for (const name of DYSFLOW_MCP_TOOL_NAMES) {
      if (getToolDefinition(name).description.trim().length < 40) tooShort.push(name);
    }
    expect(tooShort, `These tool descriptions are too short: ${tooShort.join(", ")}`).toEqual([]);
  });
});
