VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ExpedienteBusquedaTecnica"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit


Public PalabraClave As String
Public ESTADO As String
Public JURIDICA As String
Public CodExp As String
Public jp As String


Public Error As String
Private m_Error As String





