import type { DysflowMcpToolName } from "./mcp-tool-registry.js";

// Names that have a bespoke (alias) handler instead of the generic dispatch handler.
// This is the single place that says these names are not generated by the dispatch loop.
export const ALIAS_TOOL_NAME_LIST = [
  "list_access_operations",
  "cleanup_access_operation",
  "run_vba",
  "query_sql",
  "exec_sql",
  "run_script",
  "create_table",
  "drop_table",
  "seed_fixture",
  "teardown_fixture",
] as const satisfies readonly DysflowMcpToolName[];

export type AliasToolName = (typeof ALIAS_TOOL_NAME_LIST)[number];

export const ALIAS_TOOL_NAMES = new Set<DysflowMcpToolName>(ALIAS_TOOL_NAME_LIST);
