import { successResult } from "../../core/contracts/index.js";
import { buildWriteFixtureRequest } from "../../core/mapping/access-query-request-mapper.js";
import type { AccessOperationRecord } from "../../core/operations/access-operation-registry.js";
import { InMemoryAccessOperationRegistry } from "../../core/operations/access-operation-registry.js";
import {
  handleValidatedMcpWrite,
  invalidInput,
  mcpSchemaFor,
  parseMcpArgsJson,
} from "./dispatch-common.js";
import { rejectWriteSqlInReadMode } from "./dispatch-factory.js";
import { MCP_TOOL_QUERY_ACTIONS } from "./dispatch-routes.js";
import type { DysflowMcpToolName } from "./mcp-tool-registry.js";
import {
  type DysflowMcpServices,
  type DysflowMcpTool,
  type McpWriteAccessResolver,
  translateCoreResultToMcpContent,
} from "./result-translation.js";
import { NO_INPUT_SCHEMA } from "./schemas.js";
import { validateInput } from "./validator.js";

// Names that have a bespoke (alias) handler instead of the generic dispatch handler.
// This is the SINGLE place that says "these names are NOT generated by the dispatch loop" (#405).
export const ALIAS_TOOL_NAMES = new Set<DysflowMcpToolName>([
  "list_access_operations",
  "cleanup_access_operation",
  "run_vba",
  "query_sql",
  "exec_sql",
  "run_script",
  "create_table",
  "drop_table",
  "seed_fixture",
  "teardown_fixture",
]);

// ─── Alias tools ──────────────────────────────────────────────────────────────

export function buildAliasTools(
  services: DysflowMcpServices,
  writesEnabled: boolean,
  writeAccessResolver: McpWriteAccessResolver | undefined,
  allowedProcedures: readonly string[] | undefined,
): DysflowMcpTool[] {
  const cleanupSchema = mcpSchemaFor("cleanup_access_operation");
  const runVbaSchema = mcpSchemaFor("run_vba");
  const querySqlSchema = mcpSchemaFor("query_sql");
  const execSqlSchema = mcpSchemaFor("exec_sql");
  const runScriptSchema = mcpSchemaFor("run_script");
  const createTableSchema = mcpSchemaFor("create_table");
  const dropTableSchema = mcpSchemaFor("drop_table");
  const seedFixtureSchema = mcpSchemaFor("seed_fixture");
  const teardownFixtureSchema = mcpSchemaFor("teardown_fixture");

  return [
    {
      name: "list_access_operations",
      description: "Alias for listing Dysflow Access operations.",
      inputSchema: NO_INPUT_SCHEMA,
      handler: async () => {
        const registry = services.operationRegistry ?? new InMemoryAccessOperationRegistry();
        return translateCoreResultToMcpContent(
          successResult<readonly AccessOperationRecord[]>(await registry.listRecent({ limit: 50 })),
        );
      },
    },
    {
      name: "cleanup_access_operation",
      description: "Alias for safe Access operation cleanup.",
      inputSchema: cleanupSchema,
      handler: async (input) => {
        const validation = validateInput(input, cleanupSchema);
        if (validation !== undefined) return invalidInput(validation);
        if (services.cleanupService === undefined) {
          return {
            content: [
              {
                type: "text",
                text: "CLEANUP_NOT_CONFIGURED: Access cleanup service is not configured.",
              },
            ],
            isError: true,
          };
        }
        const request = input as { operationId: string; accessPath?: string; force?: boolean };
        return translateCoreResultToMcpContent(
          await services.cleanupService.cleanup({
            operationId: request.operationId,
            accessPath: request.accessPath ?? "",
            force: request.force,
          }),
        );
      },
    },
    {
      name: "run_vba",
      description: "Alias for executing a public VBA procedure.",
      inputSchema: runVbaSchema,
      handler: async (input) => {
        const validation = validateInput(input, runVbaSchema);
        if (validation !== undefined) return invalidInput(validation);
        const request = input as { procedureName: string; argsJson?: string };
        if (
          allowedProcedures !== undefined &&
          allowedProcedures.length > 0 &&
          !allowedProcedures.includes(request.procedureName)
        ) {
          return invalidInput(
            `Procedure '${request.procedureName}' is not in the configured allowedProcedures list.`,
          );
        }
        const parsedArgs = parseMcpArgsJson(request.argsJson);
        if (!parsedArgs.ok) return invalidInput(parsedArgs.message);
        return translateCoreResultToMcpContent(
          await services.vbaService.execute({
            moduleName: "",
            procedureName: request.procedureName,
            arguments: parsedArgs.value,
          }),
        );
      },
    },
    {
      name: "query_sql",
      description: "Alias for read-only Access SQL queries.",
      inputSchema: querySqlSchema,
      handler: async (input) => {
        const validation = validateInput(input, querySqlSchema);
        if (validation !== undefined) return invalidInput(validation);
        const request = input as {
          sql?: string;
          query?: string;
          backendPath?: string;
          databasePath?: string;
          sourcePath?: string;
        };
        const sql = request.sql ?? request.query ?? "";
        const sqlGuard = rejectWriteSqlInReadMode(sql);
        if (sqlGuard !== undefined) return invalidInput(sqlGuard);
        return translateCoreResultToMcpContent(
          await services.queryService.execute({
            sql,
            mode: "read",
            backendPath: request.backendPath,
            databasePath: request.databasePath ?? request.sourcePath,
          }),
        );
      },
    },
    {
      name: "exec_sql",
      description: "Alias for executing guarded Access SQL writes.",
      inputSchema: execSqlSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, execSqlSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.exec_sql, input),
          ),
        ),
    },
    {
      name: "run_script",
      description: "Alias for executing a guarded Access script.",
      inputSchema: runScriptSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, runScriptSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.run_script, input),
          ),
        ),
    },
    {
      name: "create_table",
      description: "Alias for creating a table through guarded Access writes.",
      inputSchema: createTableSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, createTableSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.create_table, input),
          ),
        ),
    },
    {
      name: "drop_table",
      description: "Alias for dropping a table through guarded Access writes.",
      inputSchema: dropTableSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, dropTableSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.drop_table, input),
          ),
        ),
    },
    {
      name: "seed_fixture",
      description: "Alias for seeding fixtures through guarded Access writes.",
      inputSchema: seedFixtureSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, seedFixtureSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.seed_fixture, input),
          ),
        ),
    },
    {
      name: "teardown_fixture",
      description: "Alias for tearing down fixtures through guarded Access writes.",
      inputSchema: teardownFixtureSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(
          input,
          teardownFixtureSchema,
          writesEnabled,
          writeAccessResolver,
          () =>
            services.queryService.execute(
              buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.teardown_fixture, input),
            ),
        ),
    },
  ];
}
