import type { AccessQueryRequest, AccessVbaRequest } from "../../core/contracts/index.js";
import { buildWriteFixtureRequest } from "../../core/mapping/access-query-request-mapper.js";
import {
  handleMcpAccessCleanup,
  handleMcpAccessOperationsList,
  handleMcpQueryExecute,
  handleMcpVbaExecute,
} from "./canonical-handlers.js";
import {
  handleValidatedMcpWrite,
  invalidInput,
  mcpSchemaFor,
  parseMcpArgsJson,
} from "./dispatch-common.js";

import { MCP_TOOL_QUERY_ACTIONS } from "./dispatch-routes.js";
import type { DysflowMcpToolName } from "./mcp-tool-registry.js";
import type {
  DysflowMcpServices,
  DysflowMcpTool,
  McpWriteAccessResolver,
} from "./result-translation.js";
import { NO_INPUT_SCHEMA } from "./schemas.js";

// Names that have a bespoke (alias) handler instead of the generic dispatch handler.
// This is the SINGLE place that says "these names are NOT generated by the dispatch loop" (#405).
export const ALIAS_TOOL_NAME_LIST = [
  "list_access_operations",
  "cleanup_access_operation",
  "run_vba",
  "query_sql",
  "exec_sql",
  "run_script",
  "create_table",
  "drop_table",
  "seed_fixture",
  "teardown_fixture",
] as const satisfies readonly DysflowMcpToolName[];

export type AliasToolName = (typeof ALIAS_TOOL_NAME_LIST)[number];

export const ALIAS_TOOL_NAMES = new Set<DysflowMcpToolName>(ALIAS_TOOL_NAME_LIST);

// ─── Alias tools ──────────────────────────────────────────────────────────────

export function buildAliasTools(
  services: DysflowMcpServices,
  writesEnabled: boolean,
  writeAccessResolver: McpWriteAccessResolver | undefined,
  allowedProcedures: readonly string[] | undefined,
): DysflowMcpTool[] {
  const cleanupSchema = mcpSchemaFor("cleanup_access_operation");
  const runVbaSchema = mcpSchemaFor("run_vba");
  const querySqlSchema = mcpSchemaFor("query_sql");
  const execSqlSchema = mcpSchemaFor("exec_sql");
  const runScriptSchema = mcpSchemaFor("run_script");
  const createTableSchema = mcpSchemaFor("create_table");
  const dropTableSchema = mcpSchemaFor("drop_table");
  const seedFixtureSchema = mcpSchemaFor("seed_fixture");
  const teardownFixtureSchema = mcpSchemaFor("teardown_fixture");

  return [
    {
      name: "list_access_operations",
      description: "Alias for listing Dysflow Access operations.",
      inputSchema: NO_INPUT_SCHEMA,
      handler: async () => handleMcpAccessOperationsList(services),
    },
    {
      name: "cleanup_access_operation",
      description: "Alias for safe Access operation cleanup.",
      inputSchema: cleanupSchema,
      handler: async (input) =>
        handleMcpAccessCleanup(
          input,
          cleanupSchema,
          services,
          writesEnabled,
          writeAccessResolver,
          (validatedInput) => {
            const request = validatedInput as {
              operationId: string;
              accessPath: string;
              force?: boolean;
              projectId?: string;
              contextId?: string;
              backendPath?: string;
              destinationRoot?: string;
              projectRoot?: string;
              timeoutMs?: number;
              strictContext?: boolean;
              expectedAccessPath?: string;
              expectedProjectRoot?: string;
              expectedDestinationRoot?: string;
            };
            return {
              operationId: request.operationId,
              accessPath: request.accessPath,
              force: request.force,
              projectId: request.projectId,
              contextId: request.contextId,
              backendPath: request.backendPath,
              destinationRoot: request.destinationRoot,
              projectRoot: request.projectRoot,
              timeoutMs: request.timeoutMs,
              strictContext: request.strictContext,
              expectedAccessPath: request.expectedAccessPath,
              expectedProjectRoot: request.expectedProjectRoot,
              expectedDestinationRoot: request.expectedDestinationRoot,
            };
          },
        ),
    },
    {
      name: "run_vba",
      description: "Alias for executing a public VBA procedure.",
      inputSchema: runVbaSchema,
      handler: async (input) =>
        handleMcpVbaExecute(input, runVbaSchema, services, allowedProcedures, (validatedInput) => {
          const request = validatedInput as {
            procedureName: string;
            argsJson?: string;
            projectId?: string;
            contextId?: string;
            accessPath?: string;
            backendPath?: string;
            destinationRoot?: string;
            projectRoot?: string;
            timeoutMs?: number;
            strictContext?: boolean;
            expectedAccessPath?: string;
            expectedProjectRoot?: string;
            expectedDestinationRoot?: string;
          };
          const parsedArgs = parseMcpArgsJson(request.argsJson);
          if (!parsedArgs.ok) return invalidInput(parsedArgs.message);
          return {
            moduleName: "",
            procedureName: request.procedureName,
            arguments: parsedArgs.value,
            projectId: request.projectId,
            contextId: request.contextId,
            accessPath: request.accessPath,
            backendPath: request.backendPath,
            destinationRoot: request.destinationRoot,
            projectRoot: request.projectRoot,
            timeoutMs: request.timeoutMs,
            strictContext: request.strictContext,
            expectedAccessPath: request.expectedAccessPath,
            expectedProjectRoot: request.expectedProjectRoot,
            expectedDestinationRoot: request.expectedDestinationRoot,
          } satisfies AccessVbaRequest;
        }),
    },
    {
      name: "query_sql",
      description: "Alias for read-only Access SQL queries.",
      inputSchema: querySqlSchema,
      handler: async (input) =>
        handleMcpQueryExecute(
          input,
          querySqlSchema,
          services,
          writesEnabled,
          writeAccessResolver,
          (validatedInput) => {
            const request = validatedInput as {
              sql?: string;
              query?: string;
              backendPath?: string;
              databasePath?: string;
              sourcePath?: string;
              projectId?: string;
              contextId?: string;
              accessPath?: string;
              destinationRoot?: string;
              projectRoot?: string;
              timeoutMs?: number;
              strictContext?: boolean;
              expectedAccessPath?: string;
              expectedProjectRoot?: string;
              expectedDestinationRoot?: string;
            };
            return {
              sql: request.sql ?? request.query ?? "",
              mode: "read",
              backendPath: request.backendPath,
              databasePath: request.databasePath ?? request.sourcePath,
              projectId: request.projectId,
              contextId: request.contextId,
              accessPath: request.accessPath,
              destinationRoot: request.destinationRoot,
              projectRoot: request.projectRoot,
              timeoutMs: request.timeoutMs,
              strictContext: request.strictContext,
              expectedAccessPath: request.expectedAccessPath,
              expectedProjectRoot: request.expectedProjectRoot,
              expectedDestinationRoot: request.expectedDestinationRoot,
            } satisfies AccessQueryRequest;
          },
        ),
    },
    {
      name: "exec_sql",
      description: "Alias for executing guarded Access SQL writes.",
      inputSchema: execSqlSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, execSqlSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.exec_sql, input),
          ),
        ),
    },
    {
      name: "run_script",
      description: "Alias for executing a guarded Access script.",
      inputSchema: runScriptSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, runScriptSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.run_script, input),
          ),
        ),
    },
    {
      name: "create_table",
      description: "Alias for creating a table through guarded Access writes.",
      inputSchema: createTableSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, createTableSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.create_table, input),
          ),
        ),
    },
    {
      name: "drop_table",
      description: "Alias for dropping a table through guarded Access writes.",
      inputSchema: dropTableSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, dropTableSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.drop_table, input),
          ),
        ),
    },
    {
      name: "seed_fixture",
      description: "Alias for seeding fixtures through guarded Access writes.",
      inputSchema: seedFixtureSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, seedFixtureSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.seed_fixture, input),
          ),
        ),
    },
    {
      name: "teardown_fixture",
      description: "Alias for tearing down fixtures through guarded Access writes.",
      inputSchema: teardownFixtureSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(
          input,
          teardownFixtureSchema,
          writesEnabled,
          writeAccessResolver,
          () =>
            services.queryService.execute(
              buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.teardown_fixture, input),
            ),
        ),
    },
  ];
}
