import type { AccessQueryRequest, AccessVbaRequest } from "../../core/contracts/index.js";
import { buildWriteFixtureRequest } from "../../core/mapping/access-query-request-mapper.js";
import {
  handleMcpAccessCleanup,
  handleMcpAccessOperationsList,
  handleMcpQueryExecute,
  handleMcpVbaExecute,
} from "./canonical-handlers.js";
import {
  handleValidatedMcpWrite,
  invalidInput,
  mcpSchemaFor,
  parseMcpArgsJson,
} from "./dispatch-common.js";

import { MCP_TOOL_QUERY_ACTIONS } from "./dispatch-routes.js";
import type { DysflowMcpToolName } from "./mcp-tool-registry.js";
import type {
  DysflowMcpServices,
  DysflowMcpTool,
  McpToolResult,
  McpWriteAccessResolver,
} from "./result-translation.js";
import { NO_INPUT_SCHEMA } from "./schemas.js";
import { TOOL_DESCRIPTIONS } from "./tool-parity-registry.js";
import { validateInput } from "./validator.js";

// Names that have a bespoke (alias) handler instead of the generic dispatch handler.
// This is the SINGLE place that says "these names are NOT generated by the dispatch loop" (#405).
export const ALIAS_TOOL_NAME_LIST = [
  "list_access_operations",
  "cleanup_access_operation",
  "run_vba",
  "query_sql",
  "exec_sql",
  "run_script",
  "create_table",
  "drop_table",
  "seed_fixture",
  "teardown_fixture",
] as const satisfies readonly DysflowMcpToolName[];

export type AliasToolName = (typeof ALIAS_TOOL_NAME_LIST)[number];

export const ALIAS_TOOL_NAMES = new Set<DysflowMcpToolName>(ALIAS_TOOL_NAME_LIST);

// ─── Typed request builders (DELTA-006) ──────────────────────────────────────
// Pure functions that read only the declared schema fields. They replace the
// structural `validatedInput as { ... }` casts previously inlined in the
// `buildAliasTools` handlers.

function isMcpToolResult(value: unknown): value is McpToolResult {
  return (
    typeof value === "object" &&
    value !== null &&
    "content" in value &&
    "isError" in value &&
    (value as { isError: unknown }).isError === true
  );
}

export { isMcpToolResult };

/**
 * Build a typed request for `cleanup_access_operation`. Reads only declared
 * fields; unknown inputs are dropped at the type boundary, not propagated.
 *
 * Schema validation (`mcpSchemaFor("cleanup_access_operation")`) is run by
 * the canonical handler BEFORE the builder, so missing required fields
 * (`operationId`, `accessPath`) are already filtered out at this point.
 */
export interface CleanupRequest {
  operationId: string;
  accessPath: string;
  force?: boolean;
  projectId?: string;
  contextId?: string;
  backendPath?: string;
  destinationRoot?: string;
  projectRoot?: string;
  timeoutMs?: number;
  strictContext?: boolean;
  expectedAccessPath?: string;
  expectedProjectRoot?: string;
  expectedDestinationRoot?: string;
}

export function buildCleanupRequest(input: unknown): CleanupRequest {
  const obj = isRecord(input) ? input : {};
  return {
    operationId: typeof obj.operationId === "string" ? obj.operationId : "",
    accessPath: typeof obj.accessPath === "string" ? obj.accessPath : "",
    force: obj.force === true ? true : undefined,
    projectId: typeof obj.projectId === "string" ? obj.projectId : undefined,
    contextId: typeof obj.contextId === "string" ? obj.contextId : undefined,
    backendPath: typeof obj.backendPath === "string" ? obj.backendPath : undefined,
    destinationRoot:
      typeof obj.destinationRoot === "string" ? obj.destinationRoot : undefined,
    projectRoot: typeof obj.projectRoot === "string" ? obj.projectRoot : undefined,
    timeoutMs: typeof obj.timeoutMs === "number" ? obj.timeoutMs : undefined,
    strictContext: obj.strictContext === true ? true : undefined,
    expectedAccessPath:
      typeof obj.expectedAccessPath === "string" ? obj.expectedAccessPath : undefined,
    expectedProjectRoot:
      typeof obj.expectedProjectRoot === "string" ? obj.expectedProjectRoot : undefined,
    expectedDestinationRoot:
      typeof obj.expectedDestinationRoot === "string"
        ? obj.expectedDestinationRoot
        : undefined,
  };
}

/**
 * Build a typed request for `run_vba`. Parses `argsJson` via the shared helper
 * and returns an `McpToolResult` (not throws) when argsJson is malformed.
 *
 * Schema validation runs BEFORE the builder via `handleMcpVbaExecute`, so
 * missing required fields (`procedureName`) are filtered out at this point.
 */
export function buildRunVbaRequest(input: unknown): AccessVbaRequest | McpToolResult {
  const obj = isRecord(input) ? input : {};
  const parsedArgs = parseMcpArgsJson(
    typeof obj.argsJson === "string" ? obj.argsJson : undefined,
  );
  if (!parsedArgs.ok) return invalidInput(parsedArgs.message);

  return {
    moduleName: "",
    procedureName: typeof obj.procedureName === "string" ? obj.procedureName : "",
    arguments: parsedArgs.value,
    projectId: typeof obj.projectId === "string" ? obj.projectId : undefined,
    contextId: typeof obj.contextId === "string" ? obj.contextId : undefined,
    accessPath: typeof obj.accessPath === "string" ? obj.accessPath : undefined,
    backendPath: typeof obj.backendPath === "string" ? obj.backendPath : undefined,
    destinationRoot: typeof obj.destinationRoot === "string" ? obj.destinationRoot : undefined,
    projectRoot: typeof obj.projectRoot === "string" ? obj.projectRoot : undefined,
    timeoutMs: typeof obj.timeoutMs === "number" ? obj.timeoutMs : undefined,
    strictContext: obj.strictContext === true ? true : undefined,
    expectedAccessPath:
      typeof obj.expectedAccessPath === "string" ? obj.expectedAccessPath : undefined,
    expectedProjectRoot:
      typeof obj.expectedProjectRoot === "string" ? obj.expectedProjectRoot : undefined,
    expectedDestinationRoot:
      typeof obj.expectedDestinationRoot === "string"
        ? obj.expectedDestinationRoot
        : undefined,
  };
}

/**
 * Build a typed request for `query_sql`. Rejects empty / whitespace-only
 * `sql` or `query` (DELTA-010) before constructing the request. Schema
 * validation runs BEFORE the builder (in the alias handler wrapper), so
 * `sql` types are already filtered; we only need to handle the
 * empty/whitespace case here.
 */
export function buildQuerySqlRequest(input: unknown): AccessQueryRequest | McpToolResult {
  if (!isRecord(input)) return invalidInput("query_sql requires an object input.");

  // DELTA-010 — reject empty/whitespace-only sql/query (was: `?? ""`).
  const rawSql = typeof input.sql === "string" ? input.sql : undefined;
  const rawQuery = typeof input.query === "string" ? input.query : undefined;
  const sql = rawSql ?? rawQuery ?? "";
  if (!sql.trim()) {
    return invalidInput("query_sql requires sql or query.");
  }

  return {
    sql,
    mode: "read",
    backendPath: typeof input.backendPath === "string" ? input.backendPath : undefined,
    databasePath:
      typeof input.databasePath === "string"
        ? input.databasePath
        : typeof input.sourcePath === "string"
          ? input.sourcePath
          : undefined,
    projectId: typeof input.projectId === "string" ? input.projectId : undefined,
    contextId: typeof input.contextId === "string" ? input.contextId : undefined,
    accessPath: typeof input.accessPath === "string" ? input.accessPath : undefined,
    destinationRoot: typeof input.destinationRoot === "string" ? input.destinationRoot : undefined,
    projectRoot: typeof input.projectRoot === "string" ? input.projectRoot : undefined,
    timeoutMs: typeof input.timeoutMs === "number" ? input.timeoutMs : undefined,
    strictContext: input.strictContext === true ? true : undefined,
    expectedAccessPath:
      typeof input.expectedAccessPath === "string" ? input.expectedAccessPath : undefined,
    expectedProjectRoot:
      typeof input.expectedProjectRoot === "string" ? input.expectedProjectRoot : undefined,
    expectedDestinationRoot:
      typeof input.expectedDestinationRoot === "string" ? input.expectedDestinationRoot : undefined,
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

// ─── Alias tools ──────────────────────────────────────────────────────────────

export function buildAliasTools(
  services: DysflowMcpServices,
  writesEnabled: boolean,
  writeAccessResolver: McpWriteAccessResolver | undefined,
  allowedProcedures: readonly string[] | undefined,
): DysflowMcpTool[] {
  const cleanupSchema = mcpSchemaFor("cleanup_access_operation");
  const runVbaSchema = mcpSchemaFor("run_vba");
  const querySqlSchema = mcpSchemaFor("query_sql");
  const execSqlSchema = mcpSchemaFor("exec_sql");
  const runScriptSchema = mcpSchemaFor("run_script");
  const createTableSchema = mcpSchemaFor("create_table");
  const dropTableSchema = mcpSchemaFor("drop_table");
  const seedFixtureSchema = mcpSchemaFor("seed_fixture");
  const teardownFixtureSchema = mcpSchemaFor("teardown_fixture");

  return [
    {
      name: "list_access_operations",
      description: TOOL_DESCRIPTIONS.list_access_operations,
      inputSchema: NO_INPUT_SCHEMA,
      handler: async () => handleMcpAccessOperationsList(services),
    },
    {
      name: "cleanup_access_operation",
      description: TOOL_DESCRIPTIONS.cleanup_access_operation,
      inputSchema: cleanupSchema,
      handler: async (input) =>
        handleMcpAccessCleanup(input, cleanupSchema, services, writesEnabled, writeAccessResolver, (validatedInput) => {
          const request = buildCleanupRequest(validatedInput);
          return {
            operationId: request.operationId,
            accessPath: request.accessPath,
            force: request.force,
            projectId: request.projectId,
            contextId: request.contextId,
            backendPath: request.backendPath,
            destinationRoot: request.destinationRoot,
            projectRoot: request.projectRoot,
            timeoutMs: request.timeoutMs,
            strictContext: request.strictContext,
            expectedAccessPath: request.expectedAccessPath,
            expectedProjectRoot: request.expectedProjectRoot,
            expectedDestinationRoot: request.expectedDestinationRoot,
          };
        }),
    },
    {
      name: "run_vba",
      description: TOOL_DESCRIPTIONS.run_vba,
      inputSchema: runVbaSchema,
      handler: async (input) =>
        handleMcpVbaExecute(input, runVbaSchema, services, allowedProcedures, (validatedInput) =>
          buildRunVbaRequest(validatedInput),
        ),
    },
    {
      name: "query_sql",
      description: TOOL_DESCRIPTIONS.query_sql,
      inputSchema: querySqlSchema,
      handler: async (input) => {
        // Run schema validation FIRST so type errors surface as schema errors
        // ("sql must be a string", etc.) before the typed builder runs. Then
        // apply the DELTA-010 empty-sql guard via the typed builder.
        const validation = validateInput(input, querySqlSchema);
        if (validation !== undefined) return invalidInput(validation);

        // DELTA-010 — empty sql/query is rejected by the builder BEFORE we
        // enter handleMcpQueryExecute (whose buildRequest signature returns
        // AccessQueryRequest only).
        const precheck = buildQuerySqlRequest(input);
        if (isMcpToolResult(precheck)) return precheck;
        return handleMcpQueryExecute(
          input,
          querySqlSchema,
          services,
          writesEnabled,
          writeAccessResolver,
          (validatedInput) => {
            const request = buildQuerySqlRequest(validatedInput);
            // Validation passed for the raw input; should not return McpToolResult
            // here, but assert defensively to keep the typed contract.
            if (isMcpToolResult(request)) {
              throw new Error("buildQuerySqlRequest returned McpToolResult after precheck passed");
            }
            return request;
          },
        );
      },
    },
    {
      name: "exec_sql",
      description: TOOL_DESCRIPTIONS.exec_sql,
      inputSchema: execSqlSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, execSqlSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.exec_sql, input),
          ),
        ),
    },
    {
      name: "run_script",
      description: TOOL_DESCRIPTIONS.run_script,
      inputSchema: runScriptSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, runScriptSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.run_script, input),
          ),
        ),
    },
    {
      name: "create_table",
      description: TOOL_DESCRIPTIONS.create_table,
      inputSchema: createTableSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, createTableSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.create_table, input),
          ),
        ),
    },
    {
      name: "drop_table",
      description: TOOL_DESCRIPTIONS.drop_table,
      inputSchema: dropTableSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, dropTableSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.drop_table, input),
          ),
        ),
    },
    {
      name: "seed_fixture",
      description: TOOL_DESCRIPTIONS.seed_fixture,
      inputSchema: seedFixtureSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(input, seedFixtureSchema, writesEnabled, writeAccessResolver, () =>
          services.queryService.execute(
            buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.seed_fixture, input),
          ),
        ),
    },
    {
      name: "teardown_fixture",
      description: TOOL_DESCRIPTIONS.teardown_fixture,
      inputSchema: teardownFixtureSchema,
      handler: async (input) =>
        handleValidatedMcpWrite(
          input,
          teardownFixtureSchema,
          writesEnabled,
          writeAccessResolver,
          () =>
            services.queryService.execute(
              buildWriteFixtureRequest(MCP_TOOL_QUERY_ACTIONS.teardown_fixture, input),
            ),
        ),
    },
  ];
}
